#!/bin/sh
echo 'Setup dirs'
/bin/busybox mkdir -p /usr/bin /usr/sbin /proc /sys /dev /sysroot /media/cdrom /media/usb /tmp /run/cryptsetup

echo 'Busybox'
/bin/busybox --install -s
export PATH=/usr/bin:/bin:/usr/sbin:/sbin

# null
[ -c /dev/null ] || mknod -m 666 /dev/null c 1 3

# sys dev
mount -t sysfs -o noexec,nosuid,nodev sysfs /sys
mount -t devtmpfs -o exec,nosuid,mode=0755,size=2M devtmpfs /dev 2>/dev/null ||
    mount -t tmpfs -o exec,nosuid,mode=0755,size=2M tmpfs /dev

# kmsg
[ -c /dev/kmsg ] || mknod -m 660 /dev/kmsg c 1 11

# proc
mount -t proc -o noexec,nosuid,nodev proc /proc
# pty device nodes (later system will need it)
[ -c /dev/ptmx ] || mknod -m 666 /dev/ptmx c 5 2
[ -d /dev/pts ] || mkdir -m 755 /dev/pts
mount -t devpts -o gid=5,mode=0620,noexec,nosuid devpts /dev/pts

# shared memory area (later system will need it)
[ -d /dev/shm ] || mkdir /dev/shm
mount -t tmpfs -o nodev,nosuid,noexec shm /dev/shm

# ln -s /proc/mounts /etc/mtab

mount -t tmpfs none /sysroot

echo 'Mount root'
mkdir -p /rom
mount "LABEL=LFD" /rom

echo 'Copy to ram'
cp -rf /rom/. /sysroot/.

umount /rom

echo 'Move dirs'
cat /proc/mounts | while read DEV DIR TYPE OPTS ; do
		if [ "$DIR" != "/" -a "$DIR" != "/sysroot" -a -d "$DIR" ]; then
			mkdir -p /sysroot/$DIR
			mount -o move $DIR /sysroot/$DIR
		fi
	done

echo 'Switch root'
exec /bin/busybox switch_root /sysroot /sbin/init
